/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'Template' 
 * Target:  'EBProject' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* Keil::Device:StdPeriph Drivers:ADC@3.5.0 */
#define RTE_DEVICE_STDPERIPH_ADC
/* Keil::Device:StdPeriph Drivers:Framework@3.5.1 */
#define RTE_DEVICE_STDPERIPH_FRAMEWORK
/* Keil::Device:StdPeriph Drivers:GPIO@3.5.0 */
#define RTE_DEVICE_STDPERIPH_GPIO
/* Keil::Device:StdPeriph Drivers:RCC@3.5.0 */
#define RTE_DEVICE_STDPERIPH_RCC
/* Keil::Device:StdPeriph Drivers:RTC@3.5.0 */
#define RTE_DEVICE_STDPERIPH_RTC
/* Keil::Device:StdPeriph Drivers:USART@3.5.0 */
#define RTE_DEVICE_STDPERIPH_USART


#endif /* RTE_COMPONENTS_H */
